.gitignore, frontend/Dockerfile
- Update node image to node 21
- Copy project.inlang before running npm ci
=> Fix and update frontend Dockerfile

frontend/playwright.config.ts, frontend/tests/e2e-tests.sh, frontend/tests/functional/detailed/common.test.ts, frontend/tests/functional/user-route.test.ts, frontend/tests/utils/form-content.ts, frontend/tests/utils/page-content.ts, frontend/tests/utils/page-detail.ts, frontend/tests/utils/test-data.ts, frontend/tests/utils/test-utils.ts
Add tests for the Users page and upgrade the e2e-tests.sh script to provide help to the developer, more options for starting tests and a better error handling
=> CA-189-add-tests-for-the-User-tab

.github/workflows/startup-tests.yml, README.md, backend/ciso_assistant/asgi.py, docker-compose.sh, docker-compose.yml, frontend/package-lock.json, frontend/package.json, frontend/playwright.config.ts
- This solves issues with Safari. The readme is updated accordingly.
- remove lost paragraphs in the readme.
=> Add caddy for docker-compose

backend/core/apps.py
update builtin roles during migration to facilitate migrations.
=> update builtin roles during migration to facilitate migrations.

backend/core/management/commands/status.py, backend/iam/views.py
The status command for manage.py allows to have a quick overview of the usage of the instance:
- number of users and how many are still first_login
- number of main objects
=> status command

frontend/Dockerfile, frontend/server/index.js
This make stopping a container immediate.
=> CA-257 catch sigint in frontend

frontend/src/lib/components/Forms/AutocompleteSelect.svelte, frontend/src/lib/components/Forms/ModelForm.svelte, frontend/src/lib/components/Forms/Select.svelte
This is a fix comming from branch [CA-252](https://github.com/intuitem/ciso-assistant-community/tree/CA-252-translate-toasts). I want to merge it earlier than the complete branch because this is an important fix.
[CA-252]: https://intuitem.atlassian.net/browse/CA-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: select choices in forms

frontend/src/lib/components/SideBar/SideBarItem.svelte, frontend/src/routes/(app)/scoring-assistant/+page.server.ts, frontend/src/routes/(app)/scoring-assistant/+page.svelte, frontend/tests/functional/nav.test.ts
Avoid modal that makes functional tests not reliable SImplify code
=> partial revert on scoring assistant

backend/app_tests/api/test_utils.py, backend/core/permissions.py, backend/core/tests/test_helpers.py, backend/core/views.py, backend/iam/models.py
for a folder, it shall return the folder itself.
=> CA-276 fix get_folder

backend/core/helpers.py
=> fix miss-alignment in bar chart

frontend/src/lib/components/Breadcrumbs/Breadcrumbs.svelte
Display the first name and last name of the user in the breadcrumb when defined instead of the email address.
=> Improve user detail view and edit view breadcrumbs

backend/core/serializers.py, frontend/src/lib/utils/table.ts
the column for risk in a risk assessment can become crowded and uneasy to read
=> Improve risk assessment display 

backend/app_tests/api/test_api_requirement_nodes.py, backend/core/apps.py, backend/core/models.py, backend/core/serializers.py, backend/core/urls.py, backend/core/views.py, backend/library/utils.py, documentation/architecture/data-model.md, tools/README.md, tools/convert_framework.py
Unused, and the word level is a bad choice.
=> Remove requirement level

backend/library/libraries/iso27001-2022.yaml, tools/convert_framework.py
add 6.3 (added in revised version of the standard)
=> Improve/iso27001 6.3

frontend/src/routes/(app)/requirement-assessments/[id=uuid]/+page.svelte
improve spacing on requirement assessment and font styling to identify the requirement easier
=> better spacing on a requirement assessment

backend/ciso_assistant/settings.py
This allows using the browsable API in debug mode
=> Allow session authentication in debug mode

backend/core/permissions.py
There is probably a better way, but this should work fine. We rely on route parsing to fix #386 .
=> #386_add special RBAC logic for approve

backend/library/libraries/matrice-des-risques-critiques-3x3.yaml, backend/library/libraries/matrice-des-risques-critiques-5x5.yaml
Traduction française de la version 3x3 et 5x5 des matrices des risques critiques.
=> Traduction FR des matrices des risques critiques

frontend/messages/en.json
"You will need to duplicate it with a different verison"
=> Fix typo in en.json

backend/core/views.py
Audits export was broken when a framework was used multiple times
=> Fix audits export with same framework

backend/library/utils.py
=> remove dead code for library management

backend/core/helpers.py
order children at the proper moment.
=> Order requirement nodes properly

backend/library/libraries/critical_risk_matrix_3x3.yaml, backend/library/libraries/critical_risk_matrix_5x5.yaml, backend/library/libraries/matrice-des-risques-critiques-3x3.yaml, backend/library/libraries/matrice-des-risques-critiques-5x5.yaml, backend/library/libraries/risk-matrix-4x4-pgssi-s-1.0.yaml, backend/library/libraries/risk-matrix-5x5-sensitive.yaml, frontend/src/lib/components/RiskMatrix/RiskMatrix.svelte, frontend/src/routes/(app)/risk-scenarios/[id=uuid]/edit/+page.svelte
Colors shall be defined for each "probability" and "impact" row in each matrix library YAML file before merging this PR.
=> Fix probability and impact unused colors

docker-compose.sh, docker-compose.yml
Since compose is in the daemon mode
=> Give the database time to finish migration 

frontend/src/lib/components/Modals/Modal.svelte, frontend/src/lib/components/Toast/Toast.svelte, frontend/src/lib/components/utils/transitions.ts, frontend/src/routes/+layout.svelte
They use @html tags, making them vulnerable to XSS.
=> Patch skeleton's Modal and Toast components

backend/core/serializers.py, backend/requirements.txt, frontend/src/lib/utils/helpers.ts
⚠️ This has to be merged **AFTER** #540 in order not to be vulnerable to XSS attacks on our Toast and Modal components.
=> Remove unnecessary sanitization

docker-compose.yml
=> fix regression

backend/core/helpers.py, backend/core/templates/core/audit_report_pdf.html, backend/core/templates/snippets/req_node.html, backend/core/templatetags/core_extras.py, backend/core/views.py
Because of #518 I looked into how the audit reports were created and saw that it could be enhanced.
This PR makes the creation of audit reports use templates, that should ease future work on them.
I tested a couple test cases and couldn't find anything modified by the new version, I hope I didn't miss anything.
=> Templatize audit reports

backend/core/models.py
I'm currently developing a feature to export an audit report that contains all the applied controls for each of the requirements of the framework, which necessitates retrieving all requirement assessments of an audit, whether they are assessable or not.
I thought I would propose this change in case you're interested in it.
=> Add optional include_non_assessable parameter to ComplianceAssessment.get_requirement_assessments

frontend/src/routes/(app)/[model=urlmodel]/+page.svelte
=> 529: fix assessment status flicker

backend/core/models.py
=> 560: propagate risk acceptance to attached scenarios

docker-compose-remote.sh, docker-compose-remote.yml
fix #578 for a better documentation with a full example
=> Update flavour for remote setup

backend/core/helpers.py
=> chore: update helpers.py

tools/cis/convert_cis.sh, tools/convert_cis.sh, tools/convert_library.py
=> fix CIS scripts

tools/ccm/convert_ccm.py, tools/ccm/convert_ccm.sh, tools/convert_ccm.sh
Add CAIQ questions as annotations
simplify and relocate script convert_ccm.sh
=> Add CAIQ to CCM

frontend/messages/en.json, frontend/messages/fr.json
fix #618 with a better explanation on clipboard support
=> Improve attachment text helper

documentation/architecture/data-model.md
=> add function to controls: spec

frontend/src/routes/(app)/scoring-assistant/utils.ts
=> switch vulnerability <-> Business impact

frontend/src/routes/(app)/frameworks/[id=uuid]/TreeViewItemContent.svelte
Ajout d'un badge même en la présence d'un seul "requirement". Cela me semble plus lisible ainsi.
=> Badge même en la présence d'un seul "requirement".

frontend/src/routes/(app)/compliance-assessments/[id=uuid]/flash-mode/+page.svelte
L'objectif de cette mise en page est de faciliter la lecture et l'utilisabilité par moins de "mouvements".
=> Proposition de nouvelle mise en page du mode "Flash"

backend/library/libraries/aircyber-v1.5.2.yaml
Before fix:
After fix and library update:
=> Fix null name for implementation groups

backend/core/migrations/0020_fix_libraries_objects_meta.py, backend/core/models.py
Before fix: ![overview_problem_libraries](https://github.com/user-attachments/assets/86ed7f36-56d0-4500-a39a-10acf1cc1c53)
After fix: ![overview_problem_libraries_fix](https://github.com/user-attachments/assets/e5eec35e-cb29-4b77-b884-428a1534526c)
=> Fix objects_meta always counting 1 object even when there is more than that

backend/core/models.py, backend/library/libraries/nist-csf-1.1.yaml, frontend/src/lib/utils/table.ts, frontend/src/routes/(app)/libraries/+page.server.ts, frontend/tests/functional/detailed/libraries.test.ts, frontend/tests/utils/page-content.ts
=> 724: improve framework naming rendering

enterprise/frontend/src/lib/components/Forms/ModelForm.svelte, frontend/src/lib/components/Forms/ModelForm.svelte
Simple code to avoid encountering the "Do you want to leave this page? Changes you made may not be saved." message when trying to leave the audit edit view without having modified anything.
will fix #758
=> Fix audit change detection

backend/core/views.py, frontend/src/routes/(app)/compliance-assessments/[id=uuid]/+page.svelte, frontend/src/routes/(app)/compliance-assessments/[id=uuid]/export/csv/+server.ts
=> Add CSV export support for Audit

documentation/architecture/data-model.md
=> Clarify TPRM spec

frontend/src/lib/utils/crud.ts, frontend/src/lib/utils/schemas.ts
=> 790 fix regression on add policy

backend/core/views.py, frontend/src/routes/(app)/[model=urlmodel]/+page.svelte, frontend/src/routes/(app)/[model=urlmodel]/export/+server.ts
- **export applied controls as csv**
- **formatting**
should fix #689
=> 689 export controls

backend/core/views.py, frontend/messages/en.json, frontend/src/lib/components/Chart/TreeChart.svelte, frontend/src/lib/components/SideBar/navData.ts, frontend/src/lib/utils/locales.ts, frontend/src/routes/(app)/x-rays/inspect/+layout.svelte, frontend/src/routes/(app)/x-rays/inspect/+page.server.ts, frontend/src/routes/(app)/x-rays/inspect/+page.svelte, frontend/tests/functional/nav.test.ts
=> First part of the inspect mode

documentation/architecture/data-model.md
add enclave principle
add conclusion field
add observation field for all assessments
=> Add enclave paradigm for TPRM implementation

frontend/src/lib/components/Modals/DisplayJSONModal.svelte, frontend/tests/functional/nav.test.ts
added functional front end tests in the about section to see if there is a build and a version well printed on screen.
=> added functional front end tests - about section

frontend/src/lib/components/Calendar/Day.svelte
bug correction on the fact that the days before the current day of the current month were filled even in the future months.
=> corrected bug on calendar - filled boxes

frontend/messages/en.json, frontend/messages/fr.json, frontend/src/routes/(app)/(internal)/x-rays/+page.svelte
Added a message when the user should create a project to use the x-rays functionality.
=> Added a message when no X-rays available

frontend/src/lib/components/Forms/Score.svelte
Disabling score editing when the result is "not applicable".
=> Disabling score when Not applicable selected

frontend/src/lib/utils/crud.ts
Add in `FIELD_COLORED_TAG_MAP` a map for policies, which is the same than applied-controls.
=> chore: Add status tag in policies list view

backend/core/serializers.py
Fixed message error on front end that was not showing properly in the case of conflicting parameters ( same name, version, etc...)
=> corrected message error on front when conflicting parameters

frontend/src/routes/(app)/(internal)/libraries/+page.svelte
=> fix delete library broken

frontend/src/routes/(app)/(internal)/libraries/+page.svelte
This reverts commit 3d2d6a73d3e2e2f001d088df61561c1fd75fe0c9.
=> Revert "fix delete library broken"

frontend/src/routes/(app)/(internal)/libraries/+page.svelte
=> fix missed change for library CRUD

frontend/tests/utils/page-content.ts
This race condition make functional tests possibly fail for all current pull requests, merge this ASAP
=> Fix functional test race condition

backend/core/startup.py, frontend/messages/en.json, frontend/messages/fr.json, frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.svelte
Add to mappings tab an import mappings button to library
=> add to mappings a import library button

backend/app_tests/api/test_api_assets.py, frontend/messages/en.json, frontend/src/lib/components/Forms/Question.svelte, frontend/tests/utils/test-utils.ts
Changed the word support to supporting in the english translation
=> changed support to supporting in english translation

frontend/src/lib/components/Forms/Question.svelte
Added a Reset button to deselect a question in the Audits with questions
=> added a reset button to questions in Audits

frontend/src/lib/components/DetailView/DetailView.svelte
fixed the errors that were not displaying in the nested list forms while it was good for the list forms.
=> fix: Error not displayed in nested list forms

frontend/src/lib/utils/table.ts
Added filter on providers in reference control tab
=> Added filter on provider for reference controls tab

.gitignore, enterprise/README.md, enterprise/backend/db/.gitignore
Added db directory so the export and migrate command works on the first load.
Added the missing steps into the documentation
=> fix & doc: Modified enterprise read me & added db directory

frontend/src/lib/components/Forms/ModelForm/EvidenceForm.svelte
Reverts intuitem/ciso-assistant-community#954
=> Revert "Display folder field in evidence when creating from it from an applied control"

frontend/src/lib/utils/i18n.ts
This first tests key, then toCamelCase(key)
=> Fix unsafeTranslate function

backend/core/helpers.py
Filtering requirement assessments by selected implementation groups in tree map
=> Filter requirement assessments by selected implementation groups in tree map

frontend/src/routes/(app)/(internal)/compliance-assessments/[id=uuid]/flash-mode/+page.svelte, frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
Can deselect a choice in flash and table mode. If its a question in table mode, it can deselect and put null value , if its a status or a result , the deselection will put again on Todo or Non assessed.
=> deselect a choice in flash and table mode

README.md
Ajout du Clausier de sécurité numérique du Club RSSI Santé aux "Community contributions"
=> Ajout du Clausier de sécurité 

charts/ciso-assistant/.helmignore, charts/ciso-assistant/Chart.yaml, charts/ciso-assistant/README.md, charts/ciso-assistant/templates/_helpers.tpl, charts/ciso-assistant/templates/configmap.yaml, charts/ciso-assistant/templates/ingress.yaml, charts/ciso-assistant/templates/secret.yaml, charts/ciso-assistant/templates/service.yaml, charts/ciso-assistant/templates/statefulset.yaml, charts/ciso-assistant/values.schema.json, charts/ciso-assistant/values.yaml
will fix #365  and then we can publish the package
=> Helm chart for CISO Assistant

backend/core/models.py
avoid crash on None when implementation group is selected.
=> Fix 500 error with CJIS flash mode

frontend/src/lib/components/DetailView/DetailView.svelte
improve detail view action button wrapping by adding a div class that space the send questionnaire button
=> Improve detail view action buttons wrapping

frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.svelte
corrected the format by putting the owner in semi-bold
=> Apply correct formatting to risk scenario owner in risk scenario detail view

backend/core/helpers.py, backend/core/models.py, backend/core/views.py, frontend/src/lib/components/Chart/StackedBarsNormalized.svelte, frontend/src/routes/(app)/(internal)/analytics/+page.svelte
- **starting point**
- **wip**
- **flip the chart**
- **Stacked bars - normalized for audits status progress**
=> stacked bars

backend/core/views.py, frontend/src/lib/utils/crud.ts
This code provokes log errors and is useless. Translating IG needs another approach.
=> remove useless ig code

frontend/src/lib/utils/table.ts
added a filter button for providers on threats tab
=> add filter on provider for threats

frontend/src/lib/components/Forms/Question.svelte, frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
Various issues with DGA questionnaire
=> Ca 543 various issues with dga questionnaire

backend/core/views.py, frontend/messages/en.json, frontend/src/lib/utils/table.ts, frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/+layout.server.ts, frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.server.ts, frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.svelte, frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/edit/+page.svelte
- **working point - naming to improve**
- **Formatter**
=> risk scenario improvement

enterprise/backend/enterprise_core/views.py
This is not ideal but it is good enough for now on this topic until we improve the code structure for BE
=> duplicate code for enterprise for Disk usage

backend/core/helpers.py, frontend/messages/en.json, frontend/messages/fr.json, frontend/src/routes/(app)/(internal)/analytics/+page.svelte
=> Add extra metrics 

enterprise/frontend/src/routes/(authentication)/login/+page.svelte, enterprise/frontend/src/routes/(authentication)/login/Greetings.svelte, frontend/src/routes/(authentication)/login/+page.svelte, frontend/src/routes/(authentication)/login/FormCard.svelte, frontend/src/routes/(authentication)/login/Greetings.svelte, frontend/src/routes/(authentication)/password-reset/+page.svelte
This PR makes the login and password reset pages more responsive when displayed on mobile phones or tablets.
=> Make Login UI responsive

documentation/architecture/data-model.md
fix ebios-rm model
ecosystem_entity -> stakeholder
=> Update data-model.md for ebios-rm (v3)

frontend/src/lib/components/DataViz/Card.svelte, frontend/src/routes/(app)/(internal)/analytics/+page.svelte, frontend/src/routes/(app)/(internal)/backup-restore/+page.svelte, frontend/src/routes/(app)/(internal)/my-assignments/+page.svelte, frontend/src/routes/(app)/+layout.svelte
This PR continues making the application more responsive on mobile:
- Sidebar menu on mobile doesn't move the entire app layout, but goes on top of it
- Analytics page is now more readable
- Backup-restore page is now more readable
=> Make the app UI more responsive

backend/core/helpers.py
=> Fix duplicate risk assessment issue

backend/.dockerignore, backend/iam/models.py
=> Fix language issue for mails

frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
- **step 1**
- **improve tablemode readibility**
=> enhance table mode

backend/core/views.py
sort scenarios by ref id to organize easily
=> sort scenarios by ref id

frontend/src/lib/components/DetailView/DetailView.svelte
Order tabs following logical order, not alphabetical order anymore so we can choose in the code what is the most important tab to display first. 
If the order is not specified for an Urlmodel, it will just do by alphabetic order as before
=> Order tabs following logical order

frontend/src/lib/utils/table.ts
added column SSO in user view table
=> added column SSO in user view table

frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
=> Temporary fix to get all the ids displayed in table mode

frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
table mode z-index correction for title with z-auto
=> table mode z-index correction for title

frontend/messages/en.json, frontend/messages/fr.json, frontend/src/lib/components/Chart/StackedBarsNormalized.svelte
translate nothing to show yet in analytics
=> translate nothing to show yet in analytics 

frontend/messages/en.json, frontend/messages/fr.json, frontend/src/lib/components/DetailView/DetailView.svelte, frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/+page.svelte, frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.svelte
traduct power-ups on applied - controls
=> traduct power-ups

frontend/src/lib/components/ModelTable/ModelTable.svelte
Added a tag for accepted risks in risk-acceptances modeltable
=> Add a tag for accepted risks

backend/core/templates/snippets/ri_list_nested.html, backend/core/views.py
- **Rename threat columns to plural threats**
- **Order risk scenarios by ref_id in risk assessment PDF export**
- **Fix display issue on unassessed scenarios**
=> CA 733 properly sort items in risk assessment pdf export

frontend/src/lib/components/CommandPalette/paletteData.ts, frontend/src/lib/components/DetailView/DetailView.svelte, frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.svelte, frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.svelte
- **read all navdata for now**
- **Fix keyboard shortcuts**
=> extra links palette and kbr shortcuts

frontend/src/lib/components/DataViz/Article.svelte
better ui on experimental tab on click (Anchor not only the title but the whole square)
=> better ui on experimental tab on click

backend/library/libraries/annex-implementing-regulation-of-nis2-on-t-m.yaml
Based on the work done by @thidalgosalvador
=> Spanish translation for NIS2 2024/2690 annex

backend/library/libraries/nis2-directive.yaml
Based on the work done by @thidalgosalvador
=> NIS2 Spanish translation yaml

backend/core/startup.py, backend/global_settings/views.py
add view_globalsettings and add is_published=True
=> Fix error when analyst creates asset

backend/core/models.py
=> Fallback to 0 on security objective value retrieval

frontend/package.json, frontend/pnpm-lock.yaml, frontend/project.inlang/settings.json
https://github.com/opral/inlang-paraglide-js/issues/304#issuecomment-2582087107
=> Hotfix: inlang build

backend/core/templates/core/base_pdf.html, backend/core/templates/snippets/mp_data.html, backend/core/templates/snippets/ra_data.html, backend/core/templates/snippets/req_node.html, backend/core/templates/snippets/ri_list_nested.html, backend/core/templates/snippets/risk_legend.html
- **split matrix into two pages to avoid breaks**
- **clean up**
- **this looks better**
- **no more breaks**
=> fix broken pdf when exporting risk analysis and the associated action plan

frontend/src/lib/utils/table.ts
Add is_third_party column in user list
=> Add is_third_party column in user list

.github/workflows/backend-api-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/startup-tests.yml
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always
=> ci: use !cancelled() rather than always()

documentation/architecture/data-model.md
Description of flollow-up and findings
=> spec: Description of follow-up and findings

charts/ciso-assistant-next/Chart.yaml, charts/ciso-assistant-next/templates/backend/deployment.yaml
1. **Added `global.domain` value to `ALLOWED_HOSTS` variable**  
The `ALLOWED_HOSTS` variable has been updated to include the `global.domain` value. This change ensures that the allowed hosts for Single Sign-On (SSO) are correctly managed, allowing requests from the defined hosts.
2. **Added and defined `HUEY_FILE_PATH` variable**  
The `HUEY_FILE_PATH` variable has been added and defined in the configuration to fix the file path for `huey.db`. This correction ensures the application works properly by specifying the correct path for the file.
- Correct handling of allowed hosts for SSO.
- Fixed the `huey.db` file path for proper functionality.
Please review and approve these changes.
=> [Helm Chart] Multiples small fixes update

charts/ciso-assistant-next/Chart.lock, charts/ciso-assistant-next/Chart.yaml, charts/ciso-assistant-next/README.md
- **fix(helm): update Chart.lock**
- **update chart version**
=> build: update chart version and fix dependencies lock

docs/deployment/deploy-on-a-vps.md
Following PR #1946 : let's add BW to the documentation once it's merged.
=> add BW note on deploy-on-a-vps.md
