intuitem/ciso-assistant-community

- frontend/src/lib/components/SideBar/navData.ts
- frontend/tests/functional/nav.test.ts
- frontend/tests/utils/page-content.ts
- frontend/tests/utils/page-detail.ts
This fix all the remaining problems
**Missing calendar tab needs to be fixed before merging**
> Fix functional tests

- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+page.svelte
This solution seems good as long as the "builtin" attribute keep the same meaning for all the models using it.
> Fix visible edit button for builtin objects

- backend/core/helpers.py
- backend/core/models.py
- backend/core/views.py
- backend/library/helpers.py
- backend/library/utils.py
fill order_id at library loading
Use order_id for sorting
When order_id is missing, use created_at instead
> CA-258 sort requirements correctly

- frontend/src/lib/components/Forms/ModelForm.svelte
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/edit/+page.svelte
I added the "origin" props to ModelForm.svelte so that we can easily create conditional statements based from where the ModelForm component is has been instantiated.
> Fix security measure's category resetting during edition

- frontend/Dockerfile
This is better for a production-grade deployment
> set Node env to production in Dockerfile

- frontend/messages/en.json
- frontend/messages/fr.json
- frontend/src/lib/components/SideBar/SideBarItem.svelte
- frontend/src/routes/(app)/risk-matrices/[id=uuid]/+server.ts
- frontend/tests/functional/nav.test.ts
- frontend/tests/functional/user-route.test.ts
- frontend/tests/utils/sidebar.ts
Things we can do in the future :
- Improve the appearance of the modal. (the 'displayJSONModal' modal type is not meant to dispay a single string).
- We could store a boolean value in the sessionStorage to track if the user has an imported risk matrix available or not in the future in order to make the load time of the scoring assistant faster (because there will be no need to fetch each time we click on the link of the scoring assistant)
> Show an error modal when trying to access the scoring assistant without an imported risk matrix

- frontend/src/lib/utils/schemas.ts
I just changed the provider field to a nullable field in the zod schema used by superform since the provider field is declared as nullable in the backend :
```
provider = models.CharField(
max_length=200, blank=True, null=True, verbose_name=_("Provider")
)
```
> Fix the error when submitting a threat edit form with a null value for the provider

- frontend/src/lib/components/Forms/ModelForm.svelte
When the creation modal is opened it will automatically make the user focus on the first text-like input, it makes things a little faster for the user and the user will never have the pain to have a modal closed because he typed on his keyboard before clicking on the input.
> Clicking on the keyboard don't close the creation modal

- frontend/src/routes/(app)/my-profile/+page.svelte
**Temporary feature**
Since a non-admin user hasn't `change_user` permission, he cannot edit its personal account and get a 403. I propose to hide this button in v1.0 as a user could only change his name (not too restrictive). We'll need to add an exception to be able to update the personal account without `change_user` permission.
> feat: temporary hide my profile edit button for non-admin

- frontend/src/lib/components/Forms/ModelForm.svelte
- frontend/src/lib/components/ModelTable/ModelTable.svelte
- frontend/src/lib/utils/crud.ts
- frontend/src/lib/utils/datetime.ts
- frontend/src/lib/utils/schemas.ts
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+layout.server.ts
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+page.server.ts
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+page.svelte
- frontend/src/routes/(app)/evidences/[id=uuid]/+page.svelte
- frontend/tests/utils/page-detail.ts
This PR adds the ability to manage applied controls' evidence through detail view. A **big** UX improvement would be to be able to create evidence directly from the create/update form.
> Allow adding evidences from applied control detail

- frontend/src/routes/(app)/risk-assessments/[id=uuid]/+page.svelte
The risk-assessment status field is nullable, but the null value can't be translated especially because paraglide refuse to store null in its message dictionary (Error: Cannot compile message with ID "null").
So my only option was to use a ternary operator to translate null into "--".
You can change it to a better text before merging this PR if you find one.
> Fix undefined risk-assessment status

- backend/core/views.py
- backend/iam/models.py
- frontend/messages/en.json
- frontend/messages/fr.json
- frontend/src/lib/utils/locales.ts
- frontend/src/routes/(app)/[model=urlmodel]/+page.server.ts
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/edit/+page.server.ts
- frontend/src/routes/(app)/users/[id=uuid]/edit/+page.server.ts
I removed import { fail } from 'assert'; in "frontend/src/routes/(app)/users/[id=uuid]/edit/+page.server.ts", it seems like it was an error surely from someone who auto-imported the wrong fail function in a previous commit.
According to this Mixin definition the "name" field isn't unique which means there may multiple UserGroup object with the same name :
```
class NameDescriptionMixin(AbstractBaseModel):
name = models.CharField(max_length=200, verbose_name=_("Name"), unique=False)
```
I am not sure having 2 user groups with the exact same name should be authorized by the application, is this normal ?
If some evil user could create a user group with the same name as the admin group and bypass some permission checks.
To address this potential issue in my code i always added builtin=True …
> Return an error message when an admin try to delete the only admin account

- backend/library/utils.py
The response time of /api/libraries was 2930ms it's now 18ms.
Only the first request to /api/libraries takes ~3000ms but all the following requests will take ~20ms with this caching mechanism.
> Implement memory caching for deserialized libary content

- frontend/src/lib/components/ModelTable/RowsPerPage.svelte
When the pagination overflows e.g: "Showing 101 to 25 of 25" it will automatically the current page number to the last (non-empty) page.
> Fix pagination overlow when changing the number of rows per page by a bigger value

- README.md
- frontend/src/lib/utils/constants.ts
- This makes life easier for developers.
- Improve the readme on how to handle production deployment.
> put default value for PUBLIC_BACKEND_API_URL in the frontend

- backend/ciso_assistant/urls.py
- backend/core/base_models.py
- backend/core/forms.py
- backend/iam/forms.py
- backend/iam/models.py
- backend/manage.py
- backend/serdes/urls.py
- backend/serdes/views.py
The login_required decorator was used before we switched to DRF to redirect to login page if there were no user authenticated. Since we were using session authentication up until recently, the decorator had no impact on the proper functioning of the view, even though it overlapped with the permission_classes.
It broke when we switched to token-based authentication, since it checks for session objects, which are no longer used.
> Remove login_required decorator

- .github/workflows/functional-tests.yml
- .github/workflows/startup-tests.yml
There seems to be an issue on Microsoft's side. See https://github.com/orgs/community/discussions/120966
Workflows fail because the runners are unable to `apt-get` packages from microsoft on `ubuntu-latest`. This PR fixes it running them on 20.04
> Run functional test workflows on Ubuntu 20.04

- backend/serdes/urls.py
- backend/serdes/views.py
This fixes the error 400 when attempting to export a backup.
The issue was due to dump_db_view being a function-based view, and thus not inheriting `settings.DEFAULT_AUTHENTICATION_CLASSES`, therefore assuming the authentication is session-based while it is in fact token-based.
> Fix error 400 when exporting backup

- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+layout.server.ts
- frontend/src/routes/(app)/[model=urlmodel]/[id=uuid]/+page.svelte
- frontend/src/routes/(app)/risk-matrices/[id=uuid]/+layout.server.ts
Risk acceptance confirm modal needs a form to be triggered since superform V2. I added a simple "id" form juste to be able to trigger it, since we don't need any information about the form.
> fix: risk acceptance actions

- backend/core/helpers.py
> #346: fix alignment in Analytics for Applied controls

- .github/workflows/backend-api-tests.yml
- .github/workflows/backend-coverage.yaml
- .github/workflows/functional-tests.yml
- .github/workflows/startup-tests.yml
- PG is running on localhost => no risk of undue access (moreover, this is only a test database)
- This will allow external PR.
- Also remove DJANGO_QECRET_KEY, which is selected randomly if not specified in environment
> use test credential for Postgres

- README.md
- backend/Dockerfile
- backend/library/utils.py
- backend/library/views.py
Got about 7x speed in yaml parsing with this tweak, if the yaml-cpp library is installed
> Switch to CLoader for yaml

- backend/core/models.py
Avoid library store error if hash changed but the triplet (urn, locale, version) is unchanged.
> avoid store conflict

- .github/workflows/functional-tests.yml
Artifacts were not uploaded anymore in the functional tests action since the split by browser of the tests
> Fix functional tests github action artifacts

- frontend/src/lib/components/Forms/FileInput.svelte
- frontend/src/lib/components/Forms/ModelForm.svelte
The Ctrl+V is only supported for images with common extensions
> Add Ctrl+V paste for evidence attachment FileInput

- frontend/src/lib/components/Forms/FileInput.svelte
Two small changes to fix screenshot filenames : 
- date.getDay() -> date.getDate()
- date.getMonth() -> date.getMonth() + 1
> Fix screenshot filename in FileInput.svelte

- backend/core/serializers.py
To resolve #534
Now html tags and attributes are still cleaned but characters like `"&", ">", ...` are unescaped
> feat: unescape html after cleaning

- frontend/src/lib/components/ModelTable/ModelTable.svelte
- frontend/src/lib/utils/crud.ts
As "actions" was a special key with a different purpose than the other keys that can be declared in the field component map, and because we might one day have a field named "actions" in some object.
We can't let the "actions" key be enumerable and let it forbid us from naming an object field "actions" just because we couldn't use a custom component to display it in the model table.
Using a Symbol for a special key like this one is cleaner.
> Use a symbol for the special actions field of the field component map

- tools/convert_library.py
Bug identified with Threats when referenced in the requirements converter.  The "threats" variable was being used multiple times and set to a string in the requirements section.  Renamed the threats array and tested with a sample file.
Appears that the threat_urn  was also missing a ":" between the urn and the part_name.
> Bug identified with Threats when referenced in the requirements

- frontend/src/routes/(app)/compliance-assessments/[id=uuid]/flash-mode/+page.server.ts
- frontend/src/routes/(app)/compliance-assessments/[id=uuid]/flash-mode/+page.svelte
In flash mode, the `not_assessed` result was assigned an empty string, while in the data model, it is represented by the string `'not_assessed'`
> Fix mismatch between data model and flash mode

- frontend/messages/fr.json
It translates to "Mesures de référence", not "Contrôles de référence"
> Fix reference controls french translation

- frontend/src/lib/utils/schemas.ts
Link fields were not allowed to be empty once they have been filled. This PR fix that.
> fix: allow empty link

- backend/iam/sso/saml/views.py
During the SSO login, if the user has not configured his first name or last name on the IdP, an error will be triggered.
This PR prevents that.
> fix: handle no first/last name during sso login

- .github/workflows/functional-tests.yml
Functional tests on firefox browser are uncertain due to dependency problems with playwright on GitHub Actions.
This PR deactivate it to to prevent checks from failing randomly.
> hotfix: firefox pipeline deactivation

- backend/iam/models.py
Make all tasks before sending mail, especially putting a superuser in the global admin group. Otherwise, the superuser can be created without any right, which makes the instance unusable.
> Avoid initialisation error in case of welcome mail sending failure

- frontend/src/routes/(app)/+layout.svelte
A squote character shifts the AppShell layout down. A quick git blame revealed that it was my mistake, sorry!
> Fix layout shifting

- frontend/src/lib/components/Forms/ModelForm.svelte
- frontend/src/lib/utils/schemas.ts
Allow to configure SSO with Identity providers which don't provide a metadata URL
> feat: allow sso configuration without metadata url

- backend/core/startup.py
- backend/iam/sso/models.py
- backend/iam/sso/saml/defaults.py
- backend/serdes/views.py
There was an issue when importing a database backup, due to `SSOSettingsQuerySet` failing to get the GlobalSettings object after a restore.
This was fixed by moving the `SSOSettings` object's creation to its queryset's first evaluation instead of post-migrate.
> Fix backup imports

- frontend/src/routes/(app)/analytics/+page.svelte
This fix only works for screen sizes with a big enough width.
> Limit the size of the framework name displayed in the used framewors BarChart

- backend/core/serializers.py
serializers.ValidationError is passed to the ViewSet and returned to the client. Displaying the message of the exception WILL cause unwanted information disclosure.
> Fix potential information disclosure

- frontend/src/lib/utils/crud.ts
If you go inside an applied control, you’ll see below its details, a table with its evidence and the possibility to manage them from the page.
We should see the list of evidence linked to a policy and be able to add them from the detail view like in an applied control.
> chore: Add nested evidence list in policies (like in applied controls)

- frontend/messages/en.json
- frontend/messages/fr.json
- frontend/src/lib/components/ModelTable/EvidenceFilePreview.svelte
- frontend/src/routes/(app)/(third-party)/evidences/[id=uuid]/+page.svelte
Added a text "No preview available" when the file of the evidence can not be previewed by the browser.
> added a text when no preview available on evidence

- frontend/.gitignore
- frontend/messages/en.json
- frontend/messages/fr.json
- frontend/src/lib/components/SideBar/SideBarCategory.svelte
- frontend/src/lib/components/SideBar/navData.ts
Translating “third party” to “gestion des tiers” results in wrong badge for TP users.
The ‘third party’ label in the sidebar should have its own identifier.
> chore: Fix thirdParty translations

- frontend/src/routes/(app)/(internal)/analytics/+page.svelte
Added a next link when editing audit in analytics to go back to analytics ( the cancel and update button were just updating the data but were not returning to a page).
> Added a next link when editing audit in analytics 

- frontend/src/lib/components/Forms/Question.svelte
When the question is too long in requirement assessments edit page, the answers are not aligned correctly.
> chore: improve question layout for Firefox

- frontend/src/lib/components/TableRowActions/TableRowActions.svelte
Quick fix to make the TableRowActions buttons as they were before with their right size, the current TableRowActions are too small.
> Fix TableRowActions button sizes

- frontend/src/lib/components/DetailView/DetailView.svelte
- frontend/src/lib/components/ModelTable/ModelTable.svelte
fixed eager datetime coercions by precising more what a date format is to the ISO regex so when you type "1000" as a name it will not show a date but just the number.
> Fix eager datetime coercions

- frontend/tailwind.config.ts
RGB gradients:
OKLCH gradients:
> Use OKLCH notation for tailwind gradients

- docker-compose.yml
- enterprise/update-ciso-assistant-enterprise.sh
- update-ciso-assistant.sh
Aims to make the locale instance update easier, faster and safer
> Add community/enterprise update script

- backend/core/helpers.py
This pull request fixes an issue that occurred when exporting a risk assessment as a PDF, the change involves updating the identifiers used in the risk matrices.
* [`backend/core/helpers.py`](diffhunk://#diff-5f32ac9fae57289f4732cb8f6a637fb8819e1afcd35eb329c1281ce510d77a6fL1052-R1054): Modified the `build_scenario_clusters` function to use `ri.ref_id` instead of `ri.rid` for adding elements to the `risk_matrix_current` and `risk_matrix_residual`.
> fix: update risk matrix to use ref_id instead of rid

- backend/ciso_assistant/settings.py
> Disable Huey from Django app

- documentation/architecture/data-model.md
Enhance project management based on PMBOK
> Update data-model for project management

- documentation/architecture/data-model.md
add ref_id/name to attack path
operational scenario corresponds to a single attack path
> clarify ebios-rm spec

- frontend/src/lib/utils/table.ts
This fixes a bug when user navigates from a project detail view to its
parent folder.
> Add null checks in table filters

- backend/core/startup.py
- backend/global_settings/views.py
- backend/iam/sso/views.py
When writing a custom `get_object` method in a viewset, we must perform call `self.check_object_permissions(request, obj)`. Otherwise, `RBACPermissions.has_object_permission` will **not** be called.
> Leverage RBAC for global settings

- .github/workflows/startup-tests.yml
- backend/Dockerfile
- backend/ciso_assistant/settings.py
- backend/startup.sh
- docker-compose-build.sh
- frontend/Dockerfile
also remove huey further,
should fix #1219
> add non-root user to frontend and backend containers

- backend/ebios_rm/views.py
- frontend/src/lib/components/Chart/EcosystemRadarChart.svelte
- frontend/src/routes/(app)/(internal)/experimental/+page.svelte
- frontend/src/routes/(app)/(internal)/experimental/ecosystem/+page.server.ts
- frontend/src/routes/(app)/(internal)/experimental/ecosystem/+page.svelte
- **starting point**
- **good step**
- **data structure**
- **good point**
> ebios stakeholders radar

- .github/workflows/functional-tests.yml
- .github/workflows/startup-tests.yml
New format is `<branch>-<timestamp>-<artifact name>`. E.g. [CA-661-git-hub-actions-find-better-names-for-uploaded-artifacts-2024-12-24T16-03-16-functional-tests-report-chromium](https://github.com/intuitem/ciso-assistant-community/actions/runs/12483668941/artifacts/2359699597)
> Rename uploaded artifacts in GitHub actions

- backend/library/utils.py
- backend/startup.sh
- update-ciso-assistant.sh
> increase wait during initialization

- backend/Dockerfile
- backend/startup.sh
- frontend/Dockerfile
multiple collisions to fix first
> Revert non-root docker user until further rework

- frontend/src/lib/utils/schemas.ts
The field is not optional at the data model level, making it optional in
the frontend is senseless.
> Require stakeholder category field

- backend/core/views.py
- frontend/src/lib/components/Forms/ModelForm/AssetForm.svelte
Users used to be able to add parent assets to a primary asset by setting its type to support, assigning parent assets, and setting its type back to primary.
This PR makes it so that it is no longer possible, and also hides the parent assets field if the asset being written is primary.
> Prevent assigning parent assets to primary assets

- frontend/src/lib/components/DetailView/DetailView.svelte
- frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/+page.svelte
- frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/edit/+page.server.ts
- frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/edit/+page.svelte
- frontend/src/routes/(app)/(third-party)/requirement-assessments/[id=uuid]/edit/+page.svelte
- **Remove obsolete workaround**
- **chore: Remove dead code**
> Fix error handling on nested create modals

- backend/core/startup.py
create superuser after library creations
> create superuser after library creations

- frontend/src/lib/components/Breadcrumbs/Breadcrumbs.svelte
- frontend/src/lib/components/ModelTable/ModelTable.svelte
I purposefully did not include next urls coming from detail views as it requires additional testing.
Including url search params in next urls coming from list views is safe however, as search params are only used for filtering in list views.
> Include search params in edit next URL when coming from list

- frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.svelte
- frontend/src/routes/(app)/(third-party)/[model=thirdparty_urlmodels]/+page.svelte
- frontend/tests/functional/user-route.test.ts
- frontend/tests/utils/base-page.ts
should help with the confusion on importing matrices and mappings
> Apply filters on catalog import for matrices and mapping

- backend/core/serializers.py
- frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/remediation-plan/+page.svelte
- **Serialize risk scenario ref_id in RiskAssessmentReadSerializer**
- **Sort risk scenarios by ref_id in risk assessment remediation plan**
> Sort remediation plan scenarios by ref id

- backend/serdes/serializers.py
- backend/serdes/tests/test_dump.py
This PR lays the groundwork for domain import/export.
The bulk of it will be located under the `serdes` django app, as it will be the basis of the upcoming work on general database dumps, moving away from stock django's `dumpdata` and `loaddata` management commands.
> Specify database dump format

- frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/TreeViewItemLead.svelte
status is for to_do, done etc... result is for not_applicable, applicable etc... someone just swapped the two notions without checking
> fix: deactivate score after scoring for not applicable requirement assessments
